version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/addon-actions"
          - "@storybook/addon-essentials"
          - "@storybook/addon-interactions"
          - "@storybook/addon-links"
          - "@storybook/react"
          - "@storybook/react-vite"
          - "@storybook/test"
      react:
        patterns:
          - "react"
          - "react-dom"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
