version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"
      npm-all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "eslint"
        versions: ["10.2.1"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
