export const breakdownSection: string;
export const breakdownItem: string;
export const breakdownLabel: string;
export const breakdownValue: string;
export const breakdownStats: string;
export const contributionDetails: string;
export const contributionItem: string;
export const contributionCount: string;
export const contributionPoints: string;
