#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test
npm run clean
npm run build
npm run lintThenTypeCopyPasteOutdatedAndAuditCheck
npm run test-storybook
rm -rf node_modules && npm run docker-test-e2e && npm install
