name: npm-test-build-upload-and-deploy-to-pages
on: [push]
jobs:
  npm-test-build-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm clean-install
      - name: Run unit tests
        run: npm run test
      - name: Run static code and project analyses
        run: npm run lintThenTypeCopyPasteOutdatedAndAuditCheck
      - name: Install end to end test browsers
        run: npx --no-install playwright install --with-deps
      - name: Run end to end tests
        run: npm run test-e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Remove development web application bundles
        run: npm run clean
      - name: Build web application bundles
        run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: dist/

  deploy-artifact-to-github-pages:
    needs: npm-test-build-and-upload-artifact
    if: github.ref == 'refs/heads/main'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-github-pages.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deploy-to-github-pages
        name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.0.9
        with:
          token: ${{ github.token }}
