name: npm-build-test-upload-artifact-and-deploy
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm clean-install
      - name: Build web application bundles
        run: npm run build
      - name: Run static code and project analyses
        run: npm run lint
      - name: Run unit tests
        run: npm run test
      - name: Install end to end test browsers
        run: npm run playwright:install
      - name: Run Storybook tests
        run: npm run storybook:test
      - name: Run end to end tests
        run: npm run docker-test-e2e

  build-upload-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-github-pages.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm clean-install
      - name: Build web application bundles
        run: npm run build
        env:
          VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ vars.VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID }}
      - name: Build static Storybook site
        run: npm run storybook:build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/
      - id: deploy-to-github-pages
        name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
